### ISSUE TITLE
Doubt regarding the data

### ISSUE THREAD

**Issue by selvamuthu** [mercerworkforceanalyticsSG/Hiring-Challenge#1]
Hello,

1) I would like to confirm the objective of this task. I am expected to analyze the data of people who left the company and find out any hidden patterns in the data which contributes to attrition. In addition, I should also propose some measures to control the attrition based on my results. Is my understanding of the objective correct?
2) I explored the data and have come up with few questions.
 Can I work on this task with some assumptions to fill in the missed values or to convert the categorical variable into dummy variable. For ex: Under Employee class, We have only one class as "Probationary" whereas rest are null/empty. So am considering the missing values as just "others".

Similarly, If required can I make some relevant assumptions with respect to data and proceed my analysis? However I will make sure to mention justifications for my reason.

Kindly request you to confirm my understanding

**Comment by asothmann** [comment]
Hi

1. Your understanding of the task is correct. I would think of the attrition problem in three parts: exploratory/descriptive (what happened e.g. who left), predictive (what is likely to happen e.g. who is likely to leave) and explanatory (why did it happen e.g. what are the factors contributing to people leaving). Based on these findings, you can then propose some action items to potentially control the attrition. 

2. Yes - please make assumptions regarding the data (the example you have provided is logical). I would strongly suggest recording the process/steps you have undertaken to transform/prepare the data along with any justifications as you have already indicated. 

Hope this helps
Aaron

**Comment by selvamuthu** [comment]
Thanks for the response. I also have another question

1) As you have already stated in the question that "2/3 of Probationary employees leave the company...",I will focus my exploratory analysis on non probationary employees, who have performance ratings based on number of years they have worked.I feel that including Probationary employees in the exploratory analysis, I would be presenting the same fact again.  

However, I understand that while building the model, I have to include all the details (Status/Employee class etc) to predict the output

Kindly request you to confirm my understanding

**Comment by selvamuthu** [comment]
Apologies. You can ignore the question about data
