### ISSUE TITLE
Query regarding 'Reason' Variable

### ISSUE THREAD

**Issue by selvamuthu** [mercerworkforceanalyticsSG/Hiring-Challenge#3]
Hi Aaron,

Can you please help me understand the value 'Merit' under Reason column?  My understanding is that based on employees performance (Merit Performance), they will be offered a raise. Employees who don't perform well, don't get a change in their pay rate. Is my understanding correct?

**Comment by asothmann** [comment]
Hi

There will typically be a number of different pay increase reasons. Generally speaking, an 'adjustment' refers to a broad increase (i.e. everyone will probably get a similar salary increase). The 'merit' increase is typically based on performance. And a 'market' adjustment is usually off-cycle to account for any significant discrepancies in pay. 

Aaron
